#!/bin/python

import urllib.request, json
#import weatherconfig

#KEY="49b81f56a6ae912a0d7d55f8647afd94"
#CITY="6173331"
UNITS="metric"
SYMBOL="°"

#city = weatherconfig.city
#api_key = weatherconfig.api_key


api='https://api.openweathermap.org/data/2.5'
api_key='49b81f56a6ae912a0d7d55f8647afd94'
city="6173331"
units="metric"

weather = eval(str(urllib.request.urlopen('{}/weather?appid={}&id={}&units={}'.format(api, api_key, city, units)).read())[2:-1])

currWeather = weather['weather'][0]

main = currWeather['main']
description = currWeather['description']

icon = ''

if main == 'Drizzle':
  #icon = ''
  icon = ' '
elif main == 'Rain':
  #icon = ''
  icon = ' '
elif main == 'Thunderstorm':
  #icon = ''
  icon = ' '
elif main == 'Snow':
  #icon = ''
  icon = ' '
elif main == 'Mist':
  #icon = ''
  icon = '  '
elif main == 'Clear':
  #icon = ''
  icon = ' '
elif main == 'Clouds':
  #icon = ''
  icon = ' '

info = description.capitalize()
#temp = int(float(weather['main']['temp']) - 272.15)
temp = int(float(weather['main']['temp']))

print('%s %s, %i °C' % (icon, main, temp))
